version: "3"
services:

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=vz5ENsAd
      - POSTGRES_USER=housekeepr
      - POSTGRES_DB=housekeepr
    volumes:
      - pgdata:/var/lib/postgresql/data

  housekeeprA:
    image: housekeepr:local
    command: bash -c "chown -R shiny:shiny /srv/hkg-data/ && env | grep 'HOUSEKEEPR\|R_DEFAULT_INTERNET_TIMEOUT' > /srv/housekeepr/.Renviron && /init"
    depends_on:
      - db
    volumes:
      - ./shiny-server.conf:/etc/shiny-server/shiny-server.conf
      - HouseKeepRDataVolume:/srv/hkg-data
    environment:
      - HOUSEKEEPR_DATADIR=/srv/hkg-data
      - HOUSEKEEPR_ENV=production
      - HOUSEKEEPR_EXTERNAL_URL=http://10.162.163.34:8098
      - R_DEFAULT_INTERNET_TIMEOUT=1800
  housekeeprB:
    image: housekeepr:local
    command: bash -c "chown -R shiny:shiny /srv/hkg-data/ && env | grep 'HOUSEKEEPR\|R_DEFAULT_INTERNET_TIMEOUT' > /srv/housekeepr/.Renviron && /init"
    depends_on:
      - db
    volumes:
      - ./shiny-server.conf:/etc/shiny-server/shiny-server.conf
      - HouseKeepRDataVolume:/srv/hkg-data
    environment:
      - HOUSEKEEPR_DATADIR=/srv/hkg-data
      - HOUSEKEEPR_ENV=production
      - HOUSEKEEPR_EXTERNAL_URL=http://10.162.163.34:8098
      - R_DEFAULT_INTERNET_TIMEOUT=1800
  housekeeprC:
    image: housekeepr:local
    command: bash -c "chown -R shiny:shiny /srv/hkg-data/ && env | grep 'HOUSEKEEPR\|R_DEFAULT_INTERNET_TIMEOUT' > /srv/housekeepr/.Renviron && /init"
    depends_on:
      - db
    volumes:
      - ./shiny-server.conf:/etc/shiny-server/shiny-server.conf
      - HouseKeepRDataVolume:/srv/hkg-data
    environment:
      - HOUSEKEEPR_DATADIR=/srv/hkg-data
      - HOUSEKEEPR_ENV=production
      - HOUSEKEEPR_EXTERNAL_URL=http://10.162.163.34:8098
      - R_DEFAULT_INTERNET_TIMEOUT=1800
  housekeeprD:
    image: housekeepr:local
    command: bash -c "chown -R shiny:shiny /srv/hkg-data/ && env | grep 'HOUSEKEEPR\|R_DEFAULT_INTERNET_TIMEOUT' > /srv/housekeepr/.Renviron && /init"
    depends_on:
      - db
    volumes:
      - ./shiny-server.conf:/etc/shiny-server/shiny-server.conf
      - HouseKeepRDataVolume:/srv/hkg-data
    environment:
      - HOUSEKEEPR_DATADIR=/srv/hkg-data
      - HOUSEKEEPR_ENV=production
      - HOUSEKEEPR_EXTERNAL_URL=http://10.162.163.34:8098
      - R_DEFAULT_INTERNET_TIMEOUT=1800
  housekeeprU:
    image: housekeepr:local
    command: bash -c "chown -R shiny:shiny /srv/hkg-data/ && env | grep 'HOUSEKEEPR\|R_DEFAULT_INTERNET_TIMEOUT' > /srv/housekeepr/.Renviron && /init"
    depends_on:
      - db
    volumes:
      - ./shiny-server.conf:/etc/shiny-server/shiny-server.conf
      - HouseKeepRDataVolume:/srv/hkg-data
    environment:
      - HOUSEKEEPR_DATADIR=/srv/hkg-data
      - HOUSEKEEPR_ENV=production
      #- HOUSEKEEPR_MODE=presentation
      - HOUSEKEEPR_EXTERNAL_URL=http://10.162.163.34:8098
      - R_DEFAULT_INTERNET_TIMEOUT=1800
  housekeeprV:
    image: housekeepr:local
    command: bash -c "chown -R shiny:shiny /srv/hkg-data/ && env | grep 'HOUSEKEEPR\|R_DEFAULT_INTERNET_TIMEOUT' > /srv/housekeepr/.Renviron && /init"
    depends_on:
      - db
    volumes:
      - ./shiny-server.conf:/etc/shiny-server/shiny-server.conf
      - HouseKeepRDataVolume:/srv/hkg-data
    environment:
      - HOUSEKEEPR_DATADIR=/srv/hkg-data
      - HOUSEKEEPR_ENV=production
      #- HOUSEKEEPR_MODE=presentation
      - HOUSEKEEPR_EXTERNAL_URL=http://10.162.163.34:8098
      - R_DEFAULT_INTERNET_TIMEOUT=1800
  housekeeprW:
    image: housekeepr:local
    command: bash -c "chown -R shiny:shiny /srv/hkg-data/ && env | grep 'HOUSEKEEPR\|R_DEFAULT_INTERNET_TIMEOUT' > /srv/housekeepr/.Renviron && /init"
    depends_on:
      - db
    volumes:
      - ./shiny-server.conf:/etc/shiny-server/shiny-server.conf
      - HouseKeepRDataVolume:/srv/hkg-data
    environment:
      - HOUSEKEEPR_DATADIR=/srv/hkg-data
      - HOUSEKEEPR_ENV=production
      #- HOUSEKEEPR_MODE=presentation
      - HOUSEKEEPR_EXTERNAL_URL=http://10.162.163.34:8098
      - R_DEFAULT_INTERNET_TIMEOUT=1800
  housekeeprX:
    image: housekeepr:local
    command: bash -c "chown -R shiny:shiny /srv/hkg-data/ && env | grep 'HOUSEKEEPR\|R_DEFAULT_INTERNET_TIMEOUT' > /srv/housekeepr/.Renviron && /init"
    depends_on:
      - db
    volumes:
      - ./shiny-server.conf:/etc/shiny-server/shiny-server.conf
      - HouseKeepRDataVolume:/srv/hkg-data
    environment:
      - HOUSEKEEPR_DATADIR=/srv/hkg-data
      - HOUSEKEEPR_ENV=production
      #- HOUSEKEEPR_MODE=presentation
      - HOUSEKEEPR_EXTERNAL_URL=http://10.162.163.34:8098
      - R_DEFAULT_INTERNET_TIMEOUT=1800

  nginx:
    build: nginx-docker
    ports:
      - "8098:80"
    #  - "8099:8080"
    links:
      - housekeeprA
      - housekeeprB
      - housekeeprC
      - housekeeprD
      - housekeeprU
      - housekeeprV
      - housekeeprW
      - housekeeprX
    volumes:
      - ./nginx-docker/nginx.conf:/opt/nginx/conf/nginx.conf


volumes:
  HouseKeepRDataVolume:
  pgdata:
